import 'package:Echo/themes/text_styles.dart';
import 'package:flutter/material.dart';

TextTheme appTextTheme() {

  return TextTheme(
    displayLarge: customTextStyle(
      fontSize: 57,
      bold: false,
      height: 64/57,
      letterSpacing: -0.25),
    displayMedium: customTextStyle(
      fontSize: 45,
      bold: false,
      height: 52/45,
      letterSpacing: 0),
    displaySmall: customTextStyle(
      fontSize: 36,
      bold: false,
      height: 44/36,
      letterSpacing: 0),
    headlineLarge: customTextStyle(
      fontSize: 32,
      bold: false,
      height: 40/32,
      letterSpacing: 0),
    headlineMedium: customTextStyle(
      fontSize: 28,
      bold: false,
      height: 36/28,
      letterSpacing: 0),
    headlineSmall: customTextStyle(
      fontSize: 24,
      bold: false,
      height: 32/24,
      letterSpacing: 0),
    titleLarge: customTextStyle(
      fontSize: 22,
      bold: false,
      height: 28/22,
      letterSpacing: 0),
    titleMedium: customTextStyle(
      fontSize: 16,
      bold: false,
      height: 24/16,
      letterSpacing: 0.15),
    titleSmall: customTextStyle(
      fontSize: 14,
      bold: false,
      height: 20/14,
      letterSpacing: 0.1),
    bodyLarge: customTextStyle(
      fontSize: 16,
      bold: false,
      height: 24/16,
      letterSpacing: 0.5),// M3 uses 0.5, M2 used 0.15
    bodyMedium: customTextStyle(
      fontSize: 14, bold: false,
      height: 20/14,
      letterSpacing: 0.25),
    bodySmall: customTextStyle(
      fontSize: 12,
      bold: false,
      height: 16/12,
      letterSpacing: 0.4),
    labelLarge: customTextStyle(
      fontSize: 14,
      bold: true,
      height: 20/14,
      letterSpacing: 0.1,
      opacity: 200/255),
    labelMedium: customTextStyle(
      fontSize: 12,
      weight: FontWeight.w500,
      height: 16/12,
      letterSpacing: 0.5,
      opacity: 200/255),
    labelSmall: customTextStyle(
      fontSize: 11,
      weight: FontWeight.w500,
      height: 16/11,
      letterSpacing: 0.5,
      opacity: 200/255),
  );
}
